namespace EVALab.Util.Graph
{
    partial class EvaListBoxCtrl
    {
        /// <summary> 
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary> 
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Component Designer generated code

        /// <summary> 
        /// Required method for Designer support - do not modify 
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            this.components = new System.ComponentModel.Container();
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(EvaListBoxCtrl));
            this.imageList1 = new System.Windows.Forms.ImageList(this.components);
            this.eListBox1 = new EVALab.Util.Graph.EListBox();
            this.SuspendLayout();
            // 
            // imageList1
            // 
            this.imageList1.ImageStream = ((System.Windows.Forms.ImageListStreamer)(resources.GetObject("imageList1.ImageStream")));
            this.imageList1.TransparentColor = System.Drawing.Color.Transparent;
            this.imageList1.Images.SetKeyName(0, "accept.png");
            this.imageList1.Images.SetKeyName(1, "add.png");
            this.imageList1.Images.SetKeyName(2, "alarm.png");
            this.imageList1.Images.SetKeyName(3, "anchor.png");
            this.imageList1.Images.SetKeyName(4, "application.png");
            this.imageList1.Images.SetKeyName(5, "application2.png");
            this.imageList1.Images.SetKeyName(6, "application_add.png");
            this.imageList1.Images.SetKeyName(7, "application_cascade.png");
            this.imageList1.Images.SetKeyName(8, "application_delete.png");
            this.imageList1.Images.SetKeyName(9, "application_double.png");
            this.imageList1.Images.SetKeyName(10, "application_edit.png");
            this.imageList1.Images.SetKeyName(11, "application_error.png");
            this.imageList1.Images.SetKeyName(12, "application_form.png");
            this.imageList1.Images.SetKeyName(13, "application_get.png");
            this.imageList1.Images.SetKeyName(14, "application_go.png");
            this.imageList1.Images.SetKeyName(15, "application_home.png");
            this.imageList1.Images.SetKeyName(16, "application_key.png");
            this.imageList1.Images.SetKeyName(17, "application_lightning.png");
            this.imageList1.Images.SetKeyName(18, "application_link.png");
            this.imageList1.Images.SetKeyName(19, "application_osx.png");
            this.imageList1.Images.SetKeyName(20, "application_osx_terminal.png");
            this.imageList1.Images.SetKeyName(21, "application_put.png");
            this.imageList1.Images.SetKeyName(22, "application_side_boxes.png");
            this.imageList1.Images.SetKeyName(23, "application_side_contract.png");
            this.imageList1.Images.SetKeyName(24, "application_side_expand.png");
            this.imageList1.Images.SetKeyName(25, "application_side_list.png");
            this.imageList1.Images.SetKeyName(26, "application_side_tree.png");
            this.imageList1.Images.SetKeyName(27, "application_split.png");
            this.imageList1.Images.SetKeyName(28, "application_tile_horizontal.png");
            this.imageList1.Images.SetKeyName(29, "application_tile_vertical.png");
            this.imageList1.Images.SetKeyName(30, "application_view_columns.png");
            this.imageList1.Images.SetKeyName(31, "application_view_detail.png");
            this.imageList1.Images.SetKeyName(32, "application_view_gallery.png");
            this.imageList1.Images.SetKeyName(33, "application_view_icons.png");
            this.imageList1.Images.SetKeyName(34, "application_view_list.png");
            this.imageList1.Images.SetKeyName(35, "application_view_tile.png");
            this.imageList1.Images.SetKeyName(36, "application_view_xp.png");
            this.imageList1.Images.SetKeyName(37, "application_view_xp_terminal.png");
            this.imageList1.Images.SetKeyName(38, "arrow_branch.png");
            this.imageList1.Images.SetKeyName(39, "arrow_divide.png");
            this.imageList1.Images.SetKeyName(40, "arrow_in.png");
            this.imageList1.Images.SetKeyName(41, "arrow_inout.png");
            this.imageList1.Images.SetKeyName(42, "arrow_join.png");
            this.imageList1.Images.SetKeyName(43, "arrow_left.png");
            this.imageList1.Images.SetKeyName(44, "arrow_merge.png");
            this.imageList1.Images.SetKeyName(45, "arrow_out.png");
            this.imageList1.Images.SetKeyName(46, "arrow_redo.png");
            this.imageList1.Images.SetKeyName(47, "arrow_refresh.png");
            this.imageList1.Images.SetKeyName(48, "arrow_right.png");
            this.imageList1.Images.SetKeyName(49, "arrow_undo.png");
            this.imageList1.Images.SetKeyName(50, "asterisk_orange.png");
            this.imageList1.Images.SetKeyName(51, "attach.png");
            this.imageList1.Images.SetKeyName(52, "attach_2.png");
            this.imageList1.Images.SetKeyName(53, "award_star_gold.png");
            this.imageList1.Images.SetKeyName(54, "bandaid.png");
            this.imageList1.Images.SetKeyName(55, "basket.png");
            this.imageList1.Images.SetKeyName(56, "bell.png");
            this.imageList1.Images.SetKeyName(57, "bin_closed.png");
            this.imageList1.Images.SetKeyName(58, "blog.png");
            this.imageList1.Images.SetKeyName(59, "blueprint.png");
            this.imageList1.Images.SetKeyName(60, "blueprint_horizontal.png");
            this.imageList1.Images.SetKeyName(61, "bluetooth.png");
            this.imageList1.Images.SetKeyName(62, "bomb.png");
            this.imageList1.Images.SetKeyName(63, "book.png");
            this.imageList1.Images.SetKeyName(64, "book_addresses.png");
            this.imageList1.Images.SetKeyName(65, "book_next.png");
            this.imageList1.Images.SetKeyName(66, "book_open.png");
            this.imageList1.Images.SetKeyName(67, "book_previous.png");
            this.imageList1.Images.SetKeyName(68, "bookmark.png");
            this.imageList1.Images.SetKeyName(69, "bookmark_book.png");
            this.imageList1.Images.SetKeyName(70, "bookmark_book_open.png");
            this.imageList1.Images.SetKeyName(71, "bookmark_document.png");
            this.imageList1.Images.SetKeyName(72, "bookmark_folder.png");
            this.imageList1.Images.SetKeyName(73, "books.png");
            this.imageList1.Images.SetKeyName(74, "box.png");
            this.imageList1.Images.SetKeyName(75, "brick.png");
            this.imageList1.Images.SetKeyName(76, "bricks.png");
            this.imageList1.Images.SetKeyName(77, "briefcase.png");
            this.imageList1.Images.SetKeyName(78, "bug.png");
            this.imageList1.Images.SetKeyName(79, "buildings.png");
            this.imageList1.Images.SetKeyName(80, "bullet_add_1.png");
            this.imageList1.Images.SetKeyName(81, "bullet_add_2.png");
            this.imageList1.Images.SetKeyName(82, "bullet_key.png");
            this.imageList1.Images.SetKeyName(83, "cake.png");
            this.imageList1.Images.SetKeyName(84, "calculator.png");
            this.imageList1.Images.SetKeyName(85, "calendar_1.png");
            this.imageList1.Images.SetKeyName(86, "calendar_2.png");
            this.imageList1.Images.SetKeyName(87, "camera.png");
            this.imageList1.Images.SetKeyName(88, "cancel.png");
            this.imageList1.Images.SetKeyName(89, "car.png");
            this.imageList1.Images.SetKeyName(90, "cart.png");
            this.imageList1.Images.SetKeyName(91, "cd.png");
            this.imageList1.Images.SetKeyName(92, "chart_bar.png");
            this.imageList1.Images.SetKeyName(93, "chart_curve.png");
            this.imageList1.Images.SetKeyName(94, "chart_line.png");
            this.imageList1.Images.SetKeyName(95, "chart_organisation.png");
            this.imageList1.Images.SetKeyName(96, "chart_pie.png");
            this.imageList1.Images.SetKeyName(97, "clipboard_paste_image.png");
            this.imageList1.Images.SetKeyName(98, "clipboard_sign.png");
            this.imageList1.Images.SetKeyName(99, "clipboard_text.png");
            this.imageList1.Images.SetKeyName(100, "clock.png");
            this.imageList1.Images.SetKeyName(101, "cog.png");
            this.imageList1.Images.SetKeyName(102, "coins.png");
            this.imageList1.Images.SetKeyName(103, "color_swatch_1.png");
            this.imageList1.Images.SetKeyName(104, "color_swatch_2.png");
            this.imageList1.Images.SetKeyName(105, "comment.png");
            this.imageList1.Images.SetKeyName(106, "compass.png");
            this.imageList1.Images.SetKeyName(107, "compress.png");
            this.imageList1.Images.SetKeyName(108, "computer.png");
            this.imageList1.Images.SetKeyName(109, "connect.png");
            this.imageList1.Images.SetKeyName(110, "contrast.png");
            this.imageList1.Images.SetKeyName(111, "control_eject.png");
            this.imageList1.Images.SetKeyName(112, "control_end.png");
            this.imageList1.Images.SetKeyName(113, "control_equalizer.png");
            this.imageList1.Images.SetKeyName(114, "control_fastforward.png");
            this.imageList1.Images.SetKeyName(115, "control_pause.png");
            this.imageList1.Images.SetKeyName(116, "control_play.png");
            this.imageList1.Images.SetKeyName(117, "control_repeat.png");
            this.imageList1.Images.SetKeyName(118, "control_rewind.png");
            this.imageList1.Images.SetKeyName(119, "control_start.png");
            this.imageList1.Images.SetKeyName(120, "control_stop.png");
            this.imageList1.Images.SetKeyName(121, "control_wheel.png");
            this.imageList1.Images.SetKeyName(122, "counter.png");
            this.imageList1.Images.SetKeyName(123, "counter_count.png");
            this.imageList1.Images.SetKeyName(124, "counter_count_up.png");
            this.imageList1.Images.SetKeyName(125, "counter_reset.png");
            this.imageList1.Images.SetKeyName(126, "counter_stop.png");
            this.imageList1.Images.SetKeyName(127, "cross.png");
            this.imageList1.Images.SetKeyName(128, "cross_octagon.png");
            this.imageList1.Images.SetKeyName(129, "cross_octagon_fram.png");
            this.imageList1.Images.SetKeyName(130, "cross_shield.png");
            this.imageList1.Images.SetKeyName(131, "cross_shield_2.png");
            this.imageList1.Images.SetKeyName(132, "crown.png");
            this.imageList1.Images.SetKeyName(133, "crown_bronze.png");
            this.imageList1.Images.SetKeyName(134, "crown_silver.png");
            this.imageList1.Images.SetKeyName(135, "css.png");
            this.imageList1.Images.SetKeyName(136, "cursor.png");
            this.imageList1.Images.SetKeyName(137, "cut.png");
            this.imageList1.Images.SetKeyName(138, "dashboard.png");
            this.imageList1.Images.SetKeyName(139, "data.png");
            this.imageList1.Images.SetKeyName(140, "database.png");
            this.imageList1.Images.SetKeyName(141, "databases.png");
            this.imageList1.Images.SetKeyName(142, "delete.png");
            this.imageList1.Images.SetKeyName(143, "delivery.png");
            this.imageList1.Images.SetKeyName(144, "desktop.png");
            this.imageList1.Images.SetKeyName(145, "desktop_empty.png");
            this.imageList1.Images.SetKeyName(146, "direction.png");
            this.imageList1.Images.SetKeyName(147, "disconnect.png");
            this.imageList1.Images.SetKeyName(148, "disk.png");
            this.imageList1.Images.SetKeyName(149, "doc_access.png");
            this.imageList1.Images.SetKeyName(150, "doc_break.png");
            this.imageList1.Images.SetKeyName(151, "doc_convert.png");
            this.imageList1.Images.SetKeyName(152, "doc_excel_csv.png");
            this.imageList1.Images.SetKeyName(153, "doc_excel_table.png");
            this.imageList1.Images.SetKeyName(154, "doc_film.png");
            this.imageList1.Images.SetKeyName(155, "doc_illustrator.png");
            this.imageList1.Images.SetKeyName(156, "doc_music.png");
            this.imageList1.Images.SetKeyName(157, "doc_music_playlist.png");
            this.imageList1.Images.SetKeyName(158, "doc_offlice.png");
            this.imageList1.Images.SetKeyName(159, "doc_page.png");
            this.imageList1.Images.SetKeyName(160, "doc_page_previous.png");
            this.imageList1.Images.SetKeyName(161, "doc_pdf.png");
            this.imageList1.Images.SetKeyName(162, "doc_photoshop.png");
            this.imageList1.Images.SetKeyName(163, "doc_resize.png");
            this.imageList1.Images.SetKeyName(164, "doc_resize_actual.png");
            this.imageList1.Images.SetKeyName(165, "doc_shred.png");
            this.imageList1.Images.SetKeyName(166, "doc_stand.png");
            this.imageList1.Images.SetKeyName(167, "doc_table.png");
            this.imageList1.Images.SetKeyName(168, "doc_tag.png");
            this.imageList1.Images.SetKeyName(169, "doc_text_image.png");
            this.imageList1.Images.SetKeyName(170, "door.png");
            this.imageList1.Images.SetKeyName(171, "door_in.png");
            this.imageList1.Images.SetKeyName(172, "drawer.png");
            this.imageList1.Images.SetKeyName(173, "drink.png");
            this.imageList1.Images.SetKeyName(174, "drink_empty.png");
            this.imageList1.Images.SetKeyName(175, "drive.png");
            this.imageList1.Images.SetKeyName(176, "drive_burn.png");
            this.imageList1.Images.SetKeyName(177, "drive_cd.png");
            this.imageList1.Images.SetKeyName(178, "drive_cd_empty.png");
            this.imageList1.Images.SetKeyName(179, "drive_delete.png");
            this.imageList1.Images.SetKeyName(180, "drive_disk.png");
            this.imageList1.Images.SetKeyName(181, "drive_error.png");
            this.imageList1.Images.SetKeyName(182, "drive_go.png");
            this.imageList1.Images.SetKeyName(183, "drive_link.png");
            this.imageList1.Images.SetKeyName(184, "drive_network.png");
            this.imageList1.Images.SetKeyName(185, "drive_rename.png");
            this.imageList1.Images.SetKeyName(186, "dvd.png");
            this.imageList1.Images.SetKeyName(187, "email.png");
            this.imageList1.Images.SetKeyName(188, "email_open.png");
            this.imageList1.Images.SetKeyName(189, "email_open_image.png");
            this.imageList1.Images.SetKeyName(190, "emoticon_evilgrin.png");
            this.imageList1.Images.SetKeyName(191, "emoticon_grin.png");
            this.imageList1.Images.SetKeyName(192, "emoticon_happy.png");
            this.imageList1.Images.SetKeyName(193, "emoticon_smile.png");
            this.imageList1.Images.SetKeyName(194, "emoticon_surprised.png");
            this.imageList1.Images.SetKeyName(195, "emoticon_tongue.png");
            this.imageList1.Images.SetKeyName(196, "emoticon_unhappy.png");
            this.imageList1.Images.SetKeyName(197, "emoticon_waii.png");
            this.imageList1.Images.SetKeyName(198, "emoticon_wink.png");
            this.imageList1.Images.SetKeyName(199, "envelope.png");
            this.imageList1.Images.SetKeyName(200, "envelope_2.png");
            this.imageList1.Images.SetKeyName(201, "error.png");
            this.imageList1.Images.SetKeyName(202, "exclamation.png");
            this.imageList1.Images.SetKeyName(203, "exclamation_octagon_fram.png");
            this.imageList1.Images.SetKeyName(204, "eye.png");
            this.imageList1.Images.SetKeyName(205, "feed.png");
            this.imageList1.Images.SetKeyName(206, "feed_ballon.png");
            this.imageList1.Images.SetKeyName(207, "feed_document.png");
            this.imageList1.Images.SetKeyName(208, "female.png");
            this.imageList1.Images.SetKeyName(209, "film.png");
            this.imageList1.Images.SetKeyName(210, "films.png");
            this.imageList1.Images.SetKeyName(211, "find.png");
            this.imageList1.Images.SetKeyName(212, "flag_blue.png");
            this.imageList1.Images.SetKeyName(213, "folder.png");
            this.imageList1.Images.SetKeyName(214, "font.png");
            this.imageList1.Images.SetKeyName(215, "funnel.png");
            this.imageList1.Images.SetKeyName(216, "grid.png");
            this.imageList1.Images.SetKeyName(217, "grid_dot.png");
            this.imageList1.Images.SetKeyName(218, "group.png");
            this.imageList1.Images.SetKeyName(219, "hammer.png");
            this.imageList1.Images.SetKeyName(220, "hammer_screwdriver.png");
            this.imageList1.Images.SetKeyName(221, "hand.png");
            this.imageList1.Images.SetKeyName(222, "hand_point.png");
            this.imageList1.Images.SetKeyName(223, "heart.png");
            this.imageList1.Images.SetKeyName(224, "heart_break.png");
            this.imageList1.Images.SetKeyName(225, "heart_empty.png");
            this.imageList1.Images.SetKeyName(226, "heart_half.png");
            this.imageList1.Images.SetKeyName(227, "heart_small.png");
            this.imageList1.Images.SetKeyName(228, "help.png");
            this.imageList1.Images.SetKeyName(229, "highlighter.png");
            this.imageList1.Images.SetKeyName(230, "house.png");
            this.imageList1.Images.SetKeyName(231, "html.png");
            this.imageList1.Images.SetKeyName(232, "image_1.png");
            this.imageList1.Images.SetKeyName(233, "image_2.png");
            this.imageList1.Images.SetKeyName(234, "images.png");
            this.imageList1.Images.SetKeyName(235, "inbox.png");
            this.imageList1.Images.SetKeyName(236, "ipod.png");
            this.imageList1.Images.SetKeyName(237, "ipod_cast.png");
            this.imageList1.Images.SetKeyName(238, "joystick.png");
            this.imageList1.Images.SetKeyName(239, "key.png");
            this.imageList1.Images.SetKeyName(240, "keyboard.png");
            this.imageList1.Images.SetKeyName(241, "layer_treansparent.png");
            this.imageList1.Images.SetKeyName(242, "layers.png");
            this.imageList1.Images.SetKeyName(243, "layout.png");
            this.imageList1.Images.SetKeyName(244, "layout_header_footer_3.png");
            this.imageList1.Images.SetKeyName(245, "layout_header_footer_3_mix.png");
            this.imageList1.Images.SetKeyName(246, "layout_join.png");
            this.imageList1.Images.SetKeyName(247, "layout_join_vertical.png");
            this.imageList1.Images.SetKeyName(248, "layout_select.png");
            this.imageList1.Images.SetKeyName(249, "layout_select_content.png");
            this.imageList1.Images.SetKeyName(250, "layout_select_footer.png");
            this.imageList1.Images.SetKeyName(251, "layout_select_sidebar.png");
            this.imageList1.Images.SetKeyName(252, "layout_split.png");
            this.imageList1.Images.SetKeyName(253, "layout_split_vertical.png");
            this.imageList1.Images.SetKeyName(254, "lifebuoy.png");
            this.imageList1.Images.SetKeyName(255, "lightbulb.png");
            this.imageList1.Images.SetKeyName(256, "lightbulb_off.png");
            this.imageList1.Images.SetKeyName(257, "lightning.png");
            this.imageList1.Images.SetKeyName(258, "link.png");
            this.imageList1.Images.SetKeyName(259, "link_break.png");
            this.imageList1.Images.SetKeyName(260, "lock.png");
            this.imageList1.Images.SetKeyName(261, "lock_unlock.png");
            this.imageList1.Images.SetKeyName(262, "magnet.png");
            this.imageList1.Images.SetKeyName(263, "magnifier.png");
            this.imageList1.Images.SetKeyName(264, "magnifier_zoom_in.png");
            this.imageList1.Images.SetKeyName(265, "male.png");
            this.imageList1.Images.SetKeyName(266, "map.png");
            this.imageList1.Images.SetKeyName(267, "marker.png");
            this.imageList1.Images.SetKeyName(268, "medal_bronze_1.png");
            this.imageList1.Images.SetKeyName(269, "medal_gold_1.png");
            this.imageList1.Images.SetKeyName(270, "media_player_small_blue.png");
            this.imageList1.Images.SetKeyName(271, "microphone.png");
            this.imageList1.Images.SetKeyName(272, "mobile_phone.png");
            this.imageList1.Images.SetKeyName(273, "money.png");
            this.imageList1.Images.SetKeyName(274, "money_dollar.png");
            this.imageList1.Images.SetKeyName(275, "money_euro.png");
            this.imageList1.Images.SetKeyName(276, "money_pound.png");
            this.imageList1.Images.SetKeyName(277, "money_yen.png");
            this.imageList1.Images.SetKeyName(278, "monitor.png");
            this.imageList1.Images.SetKeyName(279, "mouse.png");
            this.imageList1.Images.SetKeyName(280, "music.png");
            this.imageList1.Images.SetKeyName(281, "music_beam.png");
            this.imageList1.Images.SetKeyName(282, "neutral.png");
            this.imageList1.Images.SetKeyName(283, "new.png");
            this.imageList1.Images.SetKeyName(284, "newspaper.png");
            this.imageList1.Images.SetKeyName(285, "note.png");
            this.imageList1.Images.SetKeyName(286, "nuclear.png");
            this.imageList1.Images.SetKeyName(287, "package.png");
            this.imageList1.Images.SetKeyName(288, "page.png");
            this.imageList1.Images.SetKeyName(289, "page_2.png");
            this.imageList1.Images.SetKeyName(290, "page_2_copy.png");
            this.imageList1.Images.SetKeyName(291, "page_code.png");
            this.imageList1.Images.SetKeyName(292, "page_copy.png");
            this.imageList1.Images.SetKeyName(293, "page_excel.png");
            this.imageList1.Images.SetKeyName(294, "page_lightning.png");
            this.imageList1.Images.SetKeyName(295, "page_paste.png");
            this.imageList1.Images.SetKeyName(296, "page_red.png");
            this.imageList1.Images.SetKeyName(297, "page_refresh.png");
            this.imageList1.Images.SetKeyName(298, "page_save.png");
            this.imageList1.Images.SetKeyName(299, "page_white_cplusplus.png");
            this.imageList1.Images.SetKeyName(300, "page_white_csharp.png");
            this.imageList1.Images.SetKeyName(301, "page_white_cup.png");
            this.imageList1.Images.SetKeyName(302, "page_white_database.png");
            this.imageList1.Images.SetKeyName(303, "page_white_delete.png");
            this.imageList1.Images.SetKeyName(304, "page_white_dvd.png");
            this.imageList1.Images.SetKeyName(305, "page_white_edit.png");
            this.imageList1.Images.SetKeyName(306, "page_white_error.png");
            this.imageList1.Images.SetKeyName(307, "page_white_excel.png");
            this.imageList1.Images.SetKeyName(308, "page_white_find.png");
            this.imageList1.Images.SetKeyName(309, "page_white_flash.png");
            this.imageList1.Images.SetKeyName(310, "page_white_freehand.png");
            this.imageList1.Images.SetKeyName(311, "page_white_gear.png");
            this.imageList1.Images.SetKeyName(312, "page_white_get.png");
            this.imageList1.Images.SetKeyName(313, "page_white_paintbrush.png");
            this.imageList1.Images.SetKeyName(314, "page_white_paste.png");
            this.imageList1.Images.SetKeyName(315, "page_white_php.png");
            this.imageList1.Images.SetKeyName(316, "page_white_picture.png");
            this.imageList1.Images.SetKeyName(317, "page_white_powerpoint.png");
            this.imageList1.Images.SetKeyName(318, "page_white_put.png");
            this.imageList1.Images.SetKeyName(319, "page_white_ruby.png");
            this.imageList1.Images.SetKeyName(320, "page_white_stack.png");
            this.imageList1.Images.SetKeyName(321, "page_white_star.png");
            this.imageList1.Images.SetKeyName(322, "page_white_swoosh.png");
            this.imageList1.Images.SetKeyName(323, "page_white_text.png");
            this.imageList1.Images.SetKeyName(324, "page_white_text_width.png");
            this.imageList1.Images.SetKeyName(325, "page_white_tux.png");
            this.imageList1.Images.SetKeyName(326, "page_white_vector.png");
            this.imageList1.Images.SetKeyName(327, "page_white_visualstudio.png");
            this.imageList1.Images.SetKeyName(328, "page_white_width.png");
            this.imageList1.Images.SetKeyName(329, "page_white_word.png");
            this.imageList1.Images.SetKeyName(330, "page_white_world.png");
            this.imageList1.Images.SetKeyName(331, "page_white_wrench.png");
            this.imageList1.Images.SetKeyName(332, "page_white_zip.png");
            this.imageList1.Images.SetKeyName(333, "paintbrush.png");
            this.imageList1.Images.SetKeyName(334, "paintcan.png");
            this.imageList1.Images.SetKeyName(335, "palette.png");
            this.imageList1.Images.SetKeyName(336, "paper_bag.png");
            this.imageList1.Images.SetKeyName(337, "paste_plain.png");
            this.imageList1.Images.SetKeyName(338, "paste_word.png");
            this.imageList1.Images.SetKeyName(339, "pencil.png");
            this.imageList1.Images.SetKeyName(340, "photo.png");
            this.imageList1.Images.SetKeyName(341, "photo_album.png");
            this.imageList1.Images.SetKeyName(342, "photos.png");
            this.imageList1.Images.SetKeyName(343, "piano.png");
            this.imageList1.Images.SetKeyName(344, "picture.png");
            this.imageList1.Images.SetKeyName(345, "pilcrow.png");
            this.imageList1.Images.SetKeyName(346, "pill.png");
            this.imageList1.Images.SetKeyName(347, "pin.png");
            this.imageList1.Images.SetKeyName(348, "pipette.png");
            this.imageList1.Images.SetKeyName(349, "plaing_card.png");
            this.imageList1.Images.SetKeyName(350, "plug.png");
            this.imageList1.Images.SetKeyName(351, "plugin.png");
            this.imageList1.Images.SetKeyName(352, "printer.png");
            this.imageList1.Images.SetKeyName(353, "projection_screen.png");
            this.imageList1.Images.SetKeyName(354, "projection_screen_present.png");
            this.imageList1.Images.SetKeyName(355, "rainbow.png");
            this.imageList1.Images.SetKeyName(356, "report.png");
            this.imageList1.Images.SetKeyName(357, "rocket.png");
            this.imageList1.Images.SetKeyName(358, "rosette.png");
            this.imageList1.Images.SetKeyName(359, "rss.png");
            this.imageList1.Images.SetKeyName(360, "ruby.png");
            this.imageList1.Images.SetKeyName(361, "ruler_1.png");
            this.imageList1.Images.SetKeyName(362, "ruler_2.png");
            this.imageList1.Images.SetKeyName(363, "ruler_crop.png");
            this.imageList1.Images.SetKeyName(364, "ruler_triangle.png");
            this.imageList1.Images.SetKeyName(365, "safe.png");
            this.imageList1.Images.SetKeyName(366, "script.png");
            this.imageList1.Images.SetKeyName(367, "selection.png");
            this.imageList1.Images.SetKeyName(368, "selection_select.png");
            this.imageList1.Images.SetKeyName(369, "server.png");
            this.imageList1.Images.SetKeyName(370, "shading.png");
            this.imageList1.Images.SetKeyName(371, "shape_aling_bottom.png");
            this.imageList1.Images.SetKeyName(372, "shape_aling_center.png");
            this.imageList1.Images.SetKeyName(373, "shape_aling_left.png");
            this.imageList1.Images.SetKeyName(374, "shape_aling_middle.png");
            this.imageList1.Images.SetKeyName(375, "shape_aling_right.png");
            this.imageList1.Images.SetKeyName(376, "shape_aling_top.png");
            this.imageList1.Images.SetKeyName(377, "shape_flip_horizontal.png");
            this.imageList1.Images.SetKeyName(378, "shape_flip_vertical.png");
            this.imageList1.Images.SetKeyName(379, "shape_group.png");
            this.imageList1.Images.SetKeyName(380, "shape_handles.png");
            this.imageList1.Images.SetKeyName(381, "shape_move_back.png");
            this.imageList1.Images.SetKeyName(382, "shape_move_backwards.png");
            this.imageList1.Images.SetKeyName(383, "shape_move_forwards.png");
            this.imageList1.Images.SetKeyName(384, "shape_move_front.png");
            this.imageList1.Images.SetKeyName(385, "shape_square.png");
            this.imageList1.Images.SetKeyName(386, "shield.png");
            this.imageList1.Images.SetKeyName(387, "sitemap.png");
            this.imageList1.Images.SetKeyName(388, "slide.png");
            this.imageList1.Images.SetKeyName(389, "slides.png");
            this.imageList1.Images.SetKeyName(390, "slides_stack.png");
            this.imageList1.Images.SetKeyName(391, "smiley_confuse.png");
            this.imageList1.Images.SetKeyName(392, "smiley_cool.png");
            this.imageList1.Images.SetKeyName(393, "smiley_cry.png");
            this.imageList1.Images.SetKeyName(394, "smiley_fat.png");
            this.imageList1.Images.SetKeyName(395, "smiley_mad.png");
            this.imageList1.Images.SetKeyName(396, "smiley_red.png");
            this.imageList1.Images.SetKeyName(397, "smiley_roll.png");
            this.imageList1.Images.SetKeyName(398, "smiley_slim.png");
            this.imageList1.Images.SetKeyName(399, "smiley_yell.png");
            this.imageList1.Images.SetKeyName(400, "socket.png");
            this.imageList1.Images.SetKeyName(401, "sockets.png");
            this.imageList1.Images.SetKeyName(402, "sort.png");
            this.imageList1.Images.SetKeyName(403, "sort_alphabet.png");
            this.imageList1.Images.SetKeyName(404, "sort_date.png");
            this.imageList1.Images.SetKeyName(405, "sort_disable.png");
            this.imageList1.Images.SetKeyName(406, "sort_number.png");
            this.imageList1.Images.SetKeyName(407, "sort_price.png");
            this.imageList1.Images.SetKeyName(408, "sort_quantity.png");
            this.imageList1.Images.SetKeyName(409, "sort_rating.png");
            this.imageList1.Images.SetKeyName(410, "sound.png");
            this.imageList1.Images.SetKeyName(411, "sound_note.png");
            this.imageList1.Images.SetKeyName(412, "spellcheck.png");
            this.imageList1.Images.SetKeyName(413, "sport_8ball.png");
            this.imageList1.Images.SetKeyName(414, "sport_basketball.png");
            this.imageList1.Images.SetKeyName(415, "sport_football.png");
            this.imageList1.Images.SetKeyName(416, "sport_golf.png");
            this.imageList1.Images.SetKeyName(417, "sport_raquet.png");
            this.imageList1.Images.SetKeyName(418, "sport_shuttlecock.png");
            this.imageList1.Images.SetKeyName(419, "sport_soccer.png");
            this.imageList1.Images.SetKeyName(420, "sport_tennis.png");
            this.imageList1.Images.SetKeyName(421, "stamp.png");
            this.imageList1.Images.SetKeyName(422, "star_1.png");
            this.imageList1.Images.SetKeyName(423, "star_2.png");
            this.imageList1.Images.SetKeyName(424, "status_online.png");
            this.imageList1.Images.SetKeyName(425, "stop.png");
            this.imageList1.Images.SetKeyName(426, "style.png");
            this.imageList1.Images.SetKeyName(427, "sum.png");
            this.imageList1.Images.SetKeyName(428, "sum_2.png");
            this.imageList1.Images.SetKeyName(429, "switch.png");
            this.imageList1.Images.SetKeyName(430, "tab.png");
            this.imageList1.Images.SetKeyName(431, "table.png");
            this.imageList1.Images.SetKeyName(432, "tag.png");
            this.imageList1.Images.SetKeyName(433, "tag_blue.png");
            this.imageList1.Images.SetKeyName(434, "target.png");
            this.imageList1.Images.SetKeyName(435, "telephone.png");
            this.imageList1.Images.SetKeyName(436, "television.png");
            this.imageList1.Images.SetKeyName(437, "text_align_center.png");
            this.imageList1.Images.SetKeyName(438, "text_align_justify.png");
            this.imageList1.Images.SetKeyName(439, "text_align_left.png");
            this.imageList1.Images.SetKeyName(440, "text_align_right.png");
            this.imageList1.Images.SetKeyName(441, "text_allcaps.png");
            this.imageList1.Images.SetKeyName(442, "text_bold.png");
            this.imageList1.Images.SetKeyName(443, "text_columns.png");
            this.imageList1.Images.SetKeyName(444, "text_dropcaps.png");
            this.imageList1.Images.SetKeyName(445, "text_heading_1.png");
            this.imageList1.Images.SetKeyName(446, "text_horizontalrule.png");
            this.imageList1.Images.SetKeyName(447, "text_indent.png");
            this.imageList1.Images.SetKeyName(448, "text_indent_remove.png");
            this.imageList1.Images.SetKeyName(449, "text_italic.png");
            this.imageList1.Images.SetKeyName(450, "text_kerning.png");
            this.imageList1.Images.SetKeyName(451, "text_letter_omega.png");
            this.imageList1.Images.SetKeyName(452, "text_letterspacing.png");
            this.imageList1.Images.SetKeyName(453, "text_linespacing.png");
            this.imageList1.Images.SetKeyName(454, "text_list_bullets.png");
            this.imageList1.Images.SetKeyName(455, "text_list_numbers.png");
            this.imageList1.Images.SetKeyName(456, "text_lowercase.png");
            this.imageList1.Images.SetKeyName(457, "text_padding_bottom.png");
            this.imageList1.Images.SetKeyName(458, "text_padding_left.png");
            this.imageList1.Images.SetKeyName(459, "text_padding_right.png");
            this.imageList1.Images.SetKeyName(460, "text_padding_top.png");
            this.imageList1.Images.SetKeyName(461, "text_signature.png");
            this.imageList1.Images.SetKeyName(462, "text_smallcaps.png");
            this.imageList1.Images.SetKeyName(463, "text_strikethrough.png");
            this.imageList1.Images.SetKeyName(464, "text_subscript.png");
            this.imageList1.Images.SetKeyName(465, "textfield.png");
            this.imageList1.Images.SetKeyName(466, "textfield_rename.png");
            this.imageList1.Images.SetKeyName(467, "ticket.png");
            this.imageList1.Images.SetKeyName(468, "timeline_marker.png");
            this.imageList1.Images.SetKeyName(469, "traffic.png");
            this.imageList1.Images.SetKeyName(470, "transmit.png");
            this.imageList1.Images.SetKeyName(471, "trophy.png");
            this.imageList1.Images.SetKeyName(472, "trophy_bronze.png");
            this.imageList1.Images.SetKeyName(473, "trophy_silver.png");
            this.imageList1.Images.SetKeyName(474, "ui_combo_box.png");
            this.imageList1.Images.SetKeyName(475, "ui_saccordion.png");
            this.imageList1.Images.SetKeyName(476, "ui_slider_1.png");
            this.imageList1.Images.SetKeyName(477, "ui_slider_2.png");
            this.imageList1.Images.SetKeyName(478, "ui_tab_bottom.png");
            this.imageList1.Images.SetKeyName(479, "ui_tab_content.png");
            this.imageList1.Images.SetKeyName(480, "ui_tab_disable.png");
            this.imageList1.Images.SetKeyName(481, "ui_tab_side.png");
            this.imageList1.Images.SetKeyName(482, "ui_text_field_hidden.png");
            this.imageList1.Images.SetKeyName(483, "ui_text_field_password.png");
            this.imageList1.Images.SetKeyName(484, "umbrella.png");
            this.imageList1.Images.SetKeyName(485, "user.png");
            this.imageList1.Images.SetKeyName(486, "user_black_female.png");
            this.imageList1.Images.SetKeyName(487, "user_business.png");
            this.imageList1.Images.SetKeyName(488, "user_business_boss.png");
            this.imageList1.Images.SetKeyName(489, "user_female.png");
            this.imageList1.Images.SetKeyName(490, "user_silhouette.png");
            this.imageList1.Images.SetKeyName(491, "user_thief.png");
            this.imageList1.Images.SetKeyName(492, "user_thief_baldie.png");
            this.imageList1.Images.SetKeyName(493, "vcard.png");
            this.imageList1.Images.SetKeyName(494, "vector.png");
            this.imageList1.Images.SetKeyName(495, "wait.png");
            this.imageList1.Images.SetKeyName(496, "wall.png");
            this.imageList1.Images.SetKeyName(497, "wall_break.png");
            this.imageList1.Images.SetKeyName(498, "wall_brick.png");
            this.imageList1.Images.SetKeyName(499, "wall_disable.png");
            this.imageList1.Images.SetKeyName(500, "wand.png");
            this.imageList1.Images.SetKeyName(501, "weather_clouds.png");
            this.imageList1.Images.SetKeyName(502, "weather_cloudy.png");
            this.imageList1.Images.SetKeyName(503, "weather_lightning.png");
            this.imageList1.Images.SetKeyName(504, "weather_rain.png");
            this.imageList1.Images.SetKeyName(505, "weather_snow.png");
            this.imageList1.Images.SetKeyName(506, "weather_sun.png");
            this.imageList1.Images.SetKeyName(507, "webcam.png");
            this.imageList1.Images.SetKeyName(508, "world.png");
            this.imageList1.Images.SetKeyName(509, "zone.png");
            this.imageList1.Images.SetKeyName(510, "zone_money.png");
            this.imageList1.Images.SetKeyName(511, "zones.png");
            // 
            // eListBox1
            // 
            this.eListBox1.Dock = System.Windows.Forms.DockStyle.Fill;
            this.eListBox1.DrawMode = System.Windows.Forms.DrawMode.OwnerDrawFixed;
            this.eListBox1.FormattingEnabled = true;
            this.eListBox1.ImageList = this.imageList1;
            this.eListBox1.Items.AddRange(new object[] {
            "MyList"});
            this.eListBox1.Location = new System.Drawing.Point(0, 0);
            this.eListBox1.Name = "eListBox1";
            this.eListBox1.Size = new System.Drawing.Size(150, 147);
            this.eListBox1.TabIndex = 0;
            // 
            // EvaListBoxCtrl
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.Controls.Add(this.eListBox1);
            this.Name = "EvaListBoxCtrl";
            this.ResumeLayout(false);

        }

        #endregion

        private EListBox eListBox1;
        private System.Windows.Forms.ImageList imageList1;
    }
}
